### ISSUE TITLE
Artboards not reliably uploading

### ISSUE THREAD

**Issue by julianlengfelder** [marvelapp/marvelapp_sketchplugin#1]
Additionally to your known bug with artboard names, I just discovered an issue with uploading artboards named like:
- 'Artboard 1'
- 'Artboard 2'
- 'Artboard 3'
- 'Artboard 4'

The plugin often misses out on one of them. This gets even more frequent, if I already uploaded artboards with similar names before and try to update my project with new artboards.

**Comment by maximedegreve** [comment]
Hi Julian,

These artboards were duplicated right?

Max

**Comment by julianlengfelder** [comment]
Hi Max,

yes, you are right they were.
Forgot to mention that.

**Comment by maximedegreve** [comment]
Hi @julianlengfelder we might be close to a solution for this problem, it seems to be an issue on the server side rather than on the plugin side. We hope to see this automatically fixed for all the plugin users in a few days or in worst case weeks.

**Comment by julianlengfelder** [comment]
Sounds great! Will let you know if things have improved for me after the fix is deployed.

**Comment by maximedegreve** [comment]
@julianlengfelder We just deployed the fix to the server, hopefully it will work now :tada:

**Comment by julianlengfelder** [comment]
Super nice! Seems to work as expected now.👏
