### ISSUE TITLE
Turning plugin on doesn't seem to do anything

### ISSUE THREAD

**Issue by alpower** [marvelapp/marvelapp_sketchplugin#18]
Since you added the inline plugin as opposed to a modal, turning plugin on doesn't seem to do anything other than flash the screen, so have had to resort to uploading mockups manually :(

Any pointers as to where the new upload plugin should appear?

Using Mac OS X el Capitan 10.11.5 (15F34) with Sketch Version 3.8.3 (29802) on a retina macbook pro and external monitor:

Rough gif of what I'm seeing (just a screen flash):

![marvel](https://cloud.githubusercontent.com/assets/858646/16908861/831d515e-4cc6-11e6-9a2c-2cd8cd77d5dc.gif)

Any ideas how I can turn it on correctly? - maybe I'm doing something wrong. Have tried uninstalling/reinstalling plugin. Thanks in advance.

**Comment by ivostork** [comment]
I have the same issue :(

**Comment by maximedegreve** [comment]
This sounds bad, it sounds like the launcher app is not activating itself. Could you guys add me on Skype maxime.degreve ? I would like to try something with you.

**Comment by alpower** [comment]
Hi @maximedegreve - have send you a Skype contact request - thanks. Seem to have the same issue with it not working both at home and at work so can reproduce.

**Comment by maximedegreve** [comment]
After our Skype chat it looks like it's resolved with the new solution I will post next week. Thank you for the help!

**Comment by alpower** [comment]
Thanks Maxime! 👍🏻
