### ISSUE TITLE
Multiple sketch windows => Error: No artboards selected

### ISSUE THREAD

**Issue by detouch** [marvelapp/marvelapp_sketchplugin#9]
- Open multiple sketch files
- Select artboard(s)
- Send or Udpate selected artboards...
- Select a project and press _Send or update_
- Error pop-up: _You did not select any artboards_

Workaround:
Close all other open sketch files.

**Comment by maximedegreve** [comment]
Hi @detouch, did you try the latest Sketch (Version 3.4.2 15857)? There was a known bug for that in sketch...

**Comment by detouch** [comment]
yes @maximedegreve, I am using Sketch 3.4.2 (15855).
But it seems I was not using the latest marvel-sketch plugin.
Sorry, my fault.
